language: python
notifications:
  email: false
addons:
  sonarcloud:
    organization: christimperley-github
  token:
    secure: "gTYEBKOtal01Wo71xfrArQfF58IPodc1FdWeeSdqleHKYq0/xp+QQrBEOObSqL4ItOboxACkKiK/ZtqtJTLzHhnBe3pcV4pG89TPd3yUMN/FFST5/YU72xPuNyCXGCrXHj9urKWkIfkt4KbycmdGgUaJ74R2CjaQ7k02iqD3QBZ6kBzo8szbExUU/TULY2X4CYJe4LbLg6t2JOOC0ncEmII4bh5G41s6wcdDE5eMVxx0W6Z00jGnkkBDgn2exy69QZiqt2FIqtZXSsIO0Ku3QZzpXgIxer7XwFXU/ZA2krF2t/XzYQrEvpRieKDUC0YOjCtu8xasqHX0YwsxUF4vJonh7v5bLY2hr7Nk+Pz9J5O8TGBkFcv55wDezlCLBuh8Sk1oPOpncS/gc3lB6cBf1rxq5Bc8X3NpuXN17VLEjkz+9pG7ePQVVjq9r4eB8tLp+/v5Bt/wgp01vLDi9psiq9kZj6jhcMmXJaPql1wQriiErkui0lvjGL6jAytJcBZoti8zOdSVNlLX7i28dOjLgpdKPVAYfzVWrjJ0XIADo4QVa4Yn9HKLZF51rAEUzAoa/guARyJjwgAURVBXWsVwm/9vJQ4JM8sVZAkb9RPS3kdNIcoWcft26ctYEZfT2JZIl7thCAko/g9I0pMzHOG+8Quaw2PsmLvUBSgp8DDHgT0="
script:
  - sonar-scanner -X
